apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
type: Opaque
stringData:
  username: {{ .Values.postgresql.username }}
  password: {{ .Values.postgresql.password }}
  database: {{ .Values.postgresql.database }}