apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "admin123"
  DB_NAME: "configsdb"
